runtime: python37
# api_version: 1
# threadsafe: true

# libraries:
# - name: ssl
#   version: latest

handlers:
# - url: /static
#   static_dir: static
# - url: /.*
#   script: main.app

- url: /.*
  script: auto


env_variables:
    GAE_USE_SOCKETS_HTTPLIB : 'true'
